name: Women Empowerment Project
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22369
title: Tumkur Diaries
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a6beda'
    - '#090d0c'
    - '#585f71'
    - '#343b45'
    - '#cd9480'
  brandStrength: 0.0625
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
